[package]
name = "oak"
version = "0.2.0"
authors = ["Timothy Brink <contact@timothybrink.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
